version: '3'
services:
  api:
    build: .
    ports:
      - "5000:8000"
    environment:
      DATABASE_HOSTNAME: db.bmbrcteygpzrplwgfzwn.supabase.co
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: manaspat@930005
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      SECRET_KEY: mx7c1dF3CC51449E8674Abd3c60654DBbCC04211f1
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60

  postgres:
    image:
    environment:
      - POSTGRES_PASSWORD=manaspat@930005
      - POSTGRES_DB=minibackend
      
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
  
