"""auto make all the tables necessary

Revision ID: 28056300ee16
Revises: 22a94fa6bb20
Create Date: 2025-04-01 11:49:57.559532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28056300ee16'
down_revision: Union[str, None] = '22a94fa6bb20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('night')
    op.drop_column('users', 'contact_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('night',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='night_pkey')
    )
    # ### end Alembic commands ###
